<?php 
if( $this->loginEnable() == "1" && !$this->user_is_already_login() ){
  $belowLogin = $this->getBelowLogin();
  $ApiKey = trim($this->getApikey());
  $ApiSecrete = trim($this->getApiSecret());
  $loginRadiusTitle = trim( $this->getLoginRadiusTitle() );
  $UserAuth = $this->getApiResult($ApiKey, $ApiSecrete);
  if ($belowLogin == 1) {
    echo '<div class="block" style="margin-top:15px"><div class="block-title"><strong><span>'.__('Social Login').'</span></strong></div><div class="block-content"><p class="empty">';
		if($ApiKey == "" && $ApiSecrete == ""){
			echo '<p style ="color:red;">'. $this -> __('To activate your plugin, please log in to LoginRadius and get API Key & Secret. Web') .': <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
		}elseif ($UserAuth == false) {
	    echo '<p style ="color:red;">'. $this -> __('Your LoginRadius API Key and Secret is not valid, please correct it or contact LoginRadius support at') .' <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
      	}
	  else {
		echo '<div style="margin:5px"><div style="margin-bottom:5px">'.__(Mage::helper('core')->htmlEscape($loginRadiusTitle)).'</div><div class="interfacecontainerdiv"></div></div>';
	  }
    echo '</p></div></div>';
  }
}
?>