<?php 
if( $this->loginEnable() == "1" && !$this->user_is_already_login() ){
  $aboveRegister = $this->getAboveRegister();
  $ApiKey = trim($this->getApikey());
  $ApiSecrete = trim($this->getApiSecret());
  $loginRadiusTitle = trim( $this->getLoginRadiusTitle() );
  $UserAuth = $this->getApiResult($ApiKey, $ApiSecrete);
    echo '<div><h2>OR</h2>';
		if($ApiKey == "" && $ApiSecrete == ""){
			echo '<p style ="color:red;">'. $this -> __('To activate your plugin, please log in to LoginRadius and get API Key & Secret. Web') .': <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
		}elseif ($UserAuth == false) {
	    echo '<p style ="color:red;">'. $this -> __('Your LoginRadius API Key and Secret is not valid, please correct it or contact LoginRadius support at') .' <b><a href ="http://www.loginradius.com" target = "_blank">www.LoginRadius.com</a></b></p>';
      	}
	  else {
		echo '<div style="margin-bottom:5px">'.__(Mage::helper('core')->htmlEscape($loginRadiusTitle)).'</div><div class="interfacecontainerdiv"></div>';
	  }
    echo '</div>';
}
?>